// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

jQuery(function() {
  var Timecard, TimecardList, TimecardView, timecard_view;
  Timecard = (function(_super) {

    __extends(Timecard, _super);

    function Timecard() {
      return Timecard.__super__.constructor.apply(this, arguments);
    }

    Timecard.prototype.initilize = function() {
      return console.dir("Timecard#initialize");
    };

    return Timecard;

  })(Backbone.Model);
  TimecardList = (function(_super) {

    __extends(TimecardList, _super);

    function TimecardList() {
      return TimecardList.__super__.constructor.apply(this, arguments);
    }

    TimecardList.prototype.model = Timecard;

    return TimecardList;

  })(Backbone.Collection);
  TimecardView = (function(_super) {

    __extends(TimecardView, _super);

    function TimecardView() {
      return TimecardView.__super__.constructor.apply(this, arguments);
    }

    TimecardView.prototype.el = "#timecardDiv";

    TimecardView.prototype.events = {
      "click button": "addTimecard"
    };

    TimecardView.prototype.initialize = function() {
      console.dir("TimecardView#initialize");
      this.collection = new TimecardList();
      return this.collection.bind("add", this.render, this);
    };

    TimecardView.prototype.render = function(timecard) {
      return $(this.el).children("ul").append(this.template(todo));
    };

    TimecardView.prototype.addTimecard = function() {
      var timecard;
      timecard = new Timecard({
        content: $("#new-timecard").cal()
      });
      return this.collection.add(timecard);
    };

    TimecardView.prototype.template = function(timecard) {
      return "<li>" + timecard.get("content") + "</li>";
    };

    return TimecardView;

  })(Backbone.View);
  return timecard_view = new TimecardView();
});
