// Generated by CoffeeScript 1.4.0
/*
  unix timestampを取得する関数
  @param d {moment()|Number}
*/

var getUnixTimestamp, isMobile, unixTimestamp2Date;

getUnixTimestamp = function(d) {
  var dType;
  dType = typeof d;
  if (dType === 'number' || dType === 'object') {
    return moment(d).valueOf() / 1000;
  }
  return moment().valueOf() / 1000;
};

unixTimestamp2Date = function(d) {
  return moment.unix(d);
};

isMobile = (function() {

  function isMobile() {
    this.reAndroid = new RegExp(/Android/i);
    this.reBlackBerry = new RegExp(/BlackBerry/i);
    this.reIOSPhone = new RegExp(/iPhone|iPod/i);
    this.reIOSTablet = new RegExp(/iPad/i);
    this.reOperaMini = new RegExp(/Opera Mini/i);
    this.reOperaMobile = new RegExp(/Opera Mobi/i);
    this.reOperaTablet = new RegExp(/Opera Tablet/i);
    this.reWindows = new RegExp(/Windows Phone|IEMobile/i);
  }

  isMobile.prototype.Android = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return userAgent.match(this.reAndroid) !== null;
  };

  isMobile.prototype.BlackBerry = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return userAgent.match(this.reBlackBerry) !== null;
  };

  isMobile.prototype.iOSPhone = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return userAgent.match(this.reIOSPhone) !== null;
  };

  isMobile.prototype.iOSTablet = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return userAgent.match(this.reIOSTablet) !== null;
  };

  isMobile.prototype.OperaMini = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return userAgent.match(this.reOperaMini) !== null;
  };

  isMobile.prototype.OperaMobile = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return userAgent.match(this.reOperaMobile) !== null;
  };

  isMobile.prototype.OperaTablet = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return userAgent.match(this.reOperaTablet) !== null;
  };

  isMobile.prototype.Windows = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return userAgent.match(this.reWindows) !== null;
  };

  isMobile.prototype.any = function(userAgent) {
    if (userAgent == null) {
      userAgent = navigator.userAgent;
    }
    return this.BlackBerry(userAgent) || this.iOSPhone(userAgent) || this.iOSTablet(userAgent) || this.OperaMini(userAgent) || this.OperaMobile(userAgent) || this.OperaTablet(userAgent) || this.Windows(userAgent) || this.Android(userAgent);
  };

  return isMobile;

})();
